GENSTR_GIT = -DGENSTR_GIT_BRANCH="\"$(shell git rev-parse --abbrev-ref HEAD)\""        \
             -DGENSTR_GIT_CAUTHOR="\"$(shell git log -1 --format='%cn (%ce)')\""       \
             -DGENSTR_GIT_CDATE="\"$(shell git log -1 --format='%cd')\""               \
             -DGENSTR_GIT_HASH="\"$(shell git rev-parse HEAD)\""           

.PHONY: genstr_git all+

genstr_git:
	# ${GENSTR_GIT}
	rm -f Src/version.o
	rm -f stm32f407_aoa


all+: genstr_git all




